Feature/postgres readiness
ONSdigital/sdx-store pull request #38
Opened 2017-05-04 13:52 UTC by JamesGardiner

Changes the back end data store to Postgres, using SQLAlchemy as the ORM.

2017-05-04 15:12 UTC, eldeal requested changes

2017-05-04 15:12 UTC, eldeal commented on README.md
> -The query parameters for `GET /responses` match the identifying data in the Json:
The GET /responses route still seems to exist (L36 ^) so some documentation of possible query parameters may still be useful?

2017-05-04 15:12 UTC, eldeal commented on README.md
> -The query parameters for `GET /responses` match the identifying data in the Json:
Or does this route return all responses and the text describing it is just a bit misleading?

2017-05-04 15:12 UTC, eldeal commented on settings.py
> +DB_HOST = os.getenv('POSTGRES_HOST', '0.0.0.0')
No defaults please

2017-05-04 15:12 UTC, eldeal commented on server.py
> +    logger.info("Creaing tables")
Typo - creaTing

2017-05-04 15:12 UTC, eldeal commented on server.py
> +        logger.error("Could not retrieve results from db", tx_id=tx_id, invalid=invalid, e=e)
would be clearer to call the e tag error or exception for splunk

2017-05-04 15:12 UTC, eldeal commented on server.py
> +                              inserted_id=tx_id,
Can we call a fish a fish please? tx_id much easier for us to query logs on :)

2017-05-04 15:12 UTC, eldeal commented on server.py
> +    logger.error(error.message, status=400, payload=error.payload)
This payload will never be a response retrieved from a DB right? Just a tx_id or ru_ref or some identifier?

2017-05-04 15:12 UTC, eldeal commented on server.py
> +                              inserted_id=tx_id,
Though if tx_id is bound to the logger is there value in logging it here?

2017-05-04 15:12 UTC, eldeal commented on server.py
> +    if not queued:
This is my favourite change 👍

2017-05-05 07:38 UTC, JamesGardiner commented on README.md
> -The query parameters for `GET /responses` match the identifying data in the Json:
Updated in the README. Also changed refs to Mongo.

2017-05-05 07:55 UTC, JamesGardiner commented on settings.py
> +DB_HOST = os.getenv('POSTGRES_HOST', '0.0.0.0')
Waiting for https://github.com/ONSdigital/sdx-store/pull/37 to get merged and will merge those changes in

2017-05-05 12:37 UTC, warrenbailey requested changes

2017-05-05 12:37 UTC, warrenbailey commented on server.py
> +            missing = True
Not sure I see the point of the missing var, surely it could just exit that this point as soon as it finds the first missing one?

2017-05-05 12:37 UTC, warrenbailey commented on server.py
> +
These 3 functions look the same, could be rewritten as:

def queue_notification(logger, tx_id, queue):
  publisher = QueuePublisher(logger, settings.RABBIT_URLS, queue)
  return publisher.publish_message(tx_id)

2017-05-05 12:37 UTC, warrenbailey commented on server.py
> +        queued = queue_cora_notification(logger, tx_id)
I feel like i've seen this code before ^^^^, candidate for a function?

2017-05-05 12:37 UTC, warrenbailey commented on server.py
> +        return server_error("Unable to queue response")
if not queued:

2017-05-05 12:37 UTC, warrenbailey commented on settings.py
> +DB_HOST = os.getenv('POSTGRES_HOST', '0.0.0.0')
Due to the way the config works, I think we should name these env variable SDX_STORE_POSTGRES_HOST to avoid naming clashes

2017-05-05 12:37 UTC, warrenbailey commented on server.py
> +        return jsonify({}), 404
Should we be logging the error here?

2017-05-05 12:37 UTC, warrenbailey commented on settings.py
> +
Since @gavinleeedwards is removing defaults in his story, should we have default values here? or are you secretly trying to make more work for him ;)

2017-05-05 12:37 UTC, warrenbailey commented on tests/test_store.py
> +os.environ['POSTGRES_HOST'] = '0.0.0.0'
Are these needed if you're using testing.postgresql?

2017-05-05 12:38 UTC, JamesGardiner commented on server.py
> +            missing = True
I raised the same issue with @gavinleeedwards - it makes sense from a startup point of view, as you only need to fail once to understand exactly what envvars are missing.

2017-05-05 12:39 UTC, JamesGardiner commented on server.py
> +
This is technical debt from previous commits (I've just moved it). You are right though - I'll update it.

2017-05-05 12:45 UTC, warrenbailey commented on server.py
> +            missing = True
Yep makes sense, I now see the point of the missing var ;)

2017-05-05 13:13 UTC, JamesGardiner commented on server.py
> +
Done

2017-05-05 13:15 UTC, JamesGardiner commented on server.py
> +        return jsonify({}), 404
Done

2017-05-05 13:16 UTC, JamesGardiner commented on server.py
> +        queued = queue_cora_notification(logger, tx_id)
Done +1

2017-05-05 13:17 UTC, JamesGardiner commented on server.py
> +        return server_error("Unable to queue response")
Done

2017-05-05 13:17 UTC, JamesGardiner commented on settings.py
> +
Done

2017-05-05 13:19 UTC, JamesGardiner commented on tests/test_store.py
> +os.environ['POSTGRES_HOST'] = '0.0.0.0'
Do you mean the setting of the env vars? Tests fail without it

2017-05-05 13:21 UTC, JamesGardiner commented on settings.py
> +DB_HOST = os.getenv('POSTGRES_HOST', '0.0.0.0')
Done

2017-05-05 13:33 UTC, warrenbailey approved these changes

2017-05-08 09:59 UTC, necrophonic commented on server.py
> +    logger.error(error.message, status=400, payload=error.payload)
Looks like mostly the request args passed into a search?

2017-05-08 10:10 UTC, JamesGardiner commented on server.py
> +    logger.error(error.message, status=400, payload=error.payload)
No - just the traceback for any error where specified. By it's nature this isn't called when a db succesfully responds.

2017-05-08 10:21 UTC, eldeal approved these changes

2017-05-09 11:05 UTC, merged