Fix/publish with tx id in header
ONSdigital/sdx-store pull request #70
Opened 2017-08-08 10:31 UTC by tej99

## What? and Why?
> What does this pull request change/fix? Why was it nessessary?
Added the tx_id to the header of the message to be queued for downstream support. 

## Checklist
  - [ ] CHANGELOG.md updated? (if required)

2017-08-08 10:31 UTC, tej99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Improve sdx-downstream error response handling](https://trello.com/c/6C6mtGiB/231-5-improve-sdx-downstream-error-response-handling)

2017-08-08 14:05 UTC, necrophonic commented on queue_publisher.py
> +    def _publish(self, message, tx_id):
The message _is_ the `tx_id` so no need to pass the same thing twice. Maybe better to just rename the `message` parameter, or pass `message` into the `tx_id` header.

2017-08-11 10:25 UTC, JamesGardiner requested changes

2017-08-11 10:25 UTC, JamesGardiner commented on server.py
> +    tx_id = request.get_json(force=True)['tx_id']
We should probably use a try except block here to handle exceptions where there is no tx_id present.

2017-08-14 09:03 UTC, JamesGardiner approved these changes

2017-08-14 09:03 UTC, merged