Removed sdx common clone in dockerfile
ONSdigital/sdx-store pull request #77
Opened 2017-09-13 09:16 UTC by emilioward

## What? and Why?
> What does this pull request change/fix? Why was it necessary?

This PR fixes the issue of a cryptography error when running docker build in sdx-store 

## Checklist
  - [x] CHANGELOG.md updated? (if required)

2017-09-13 09:17 UTC, emilioward commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Remove sdx common clone in Dockerfiles](https://trello.com/c/AfHeYs4M/400-3-remove-sdx-common-clone-in-dockerfiles)

2017-09-13 09:27 UTC, necrophonic requested changes

2017-09-13 09:27 UTC, necrophonic commented on Dockerfile
> +FROM onsdigital/flask-crypto-queue
Should only have the single `FROM` - don't need the `ubuntu` one

2017-09-14 13:23 UTC, JamesGardiner submitted a review, later dismissed

2017-09-15 08:51 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Remove sdx common clone in Dockerfiles](https://trello.com/c/AfHeYs4M/400-3-remove-sdx-common-clone-in-dockerfiles)

2017-09-20 13:41 UTC, dcdarrell9 approved these changes
Works for me 👍

2017-09-20 14:27 UTC, necrophonic approved these changes

2017-09-20 14:29 UTC, merged